import linkage_complete_intersections_determinantal_ideals_lemma_canonical_lane_mathlib.GateLemmas
import linkage_complete_intersections_determinantal_ideals_lemma_canonical_lane_mathlib.FinalTheorem
