import linkage_complete_intersections_determinantal_ideals_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace linkage_complete_intersections_determinantal_ideals_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end linkage_complete_intersections_determinantal_ideals_lemma_canonical_lane_mathlib
end HautevilleHouse
